name: handwerker_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
